extends: plumber:default
version: "2.0"

github:
  controls:
    workflowMustIncludeRequiredActions:
      enabled: true
      required: gitleaks/gitleaks-action AND aquasecurity/trivy-action AND getplumber/plumber
