from __future__ import annotations

from pathlib import Path

import yaml

GENERATED_MARKER = "# Generated by Portabase CLI"


class ComposeFacts:
    def __init__(self, path: Path) -> None:
        self.path = path
        self.raw: dict = {}
        self.text = ""
        if path.exists():
            try:
                self.text = path.read_text(encoding="utf-8")
                loaded = yaml.safe_load(self.text)
                self.raw = loaded if isinstance(loaded, dict) else {}
            except (OSError, yaml.YAMLError):
                self.raw = {}

    @property
    def exists(self) -> bool:
        return self.path.exists()

    @property
    def is_generated(self) -> bool:
        return self.text.startswith(GENERATED_MARKER)

    def _service(self, name: str) -> dict:
        services = self.raw.get("services") or {}
        svc = services.get(name) if isinstance(services, dict) else None
        return svc if isinstance(svc, dict) else {}

    @property
    def host_gateway(self) -> bool:
        extra = self._service("agent").get("extra_hosts")
        if isinstance(extra, list):
            return any("host-gateway" in str(x) for x in extra)
        if isinstance(extra, dict):
            return any("host-gateway" in str(v) for v in extra.values())
        return False
