name: test-agent
services:
  app:
    container_name: test-agent-app
    restart: always
    image: portabase/agent:latest
    volumes:
      - ./databases.json:/config/config.json
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      TZ: "Europe/Paris"
      EDGE_KEY: "${EDGE_KEY}"
      LOG: info
    networks:
      - portabase


  db-valkey-auth-ca0c:
    image: valkey/valkey:latest
    container_name: test-agent-db-valkey-auth-ca0c
    command: --requirepass "${DB_VALKEY_AUTH_CA0C_PASS}"
    ports:
      - "${DB_VALKEY_AUTH_CA0C_PORT}:6379"
    volumes:
      - db-valkey-auth-ca0c-data:/data
    networks:
      - portabase
      - default

  db-redis-auth-e7e4:
    image: redis:latest
    container_name: test-agent-db-redis-auth-e7e4
    ports:
      - "${DB_REDIS_AUTH_E7E4_PORT}:6379"
    volumes:
      - db-redis-auth-e7e4-data:/data
    environment:
      - REDIS_PASSWORD=${DB_REDIS_AUTH_E7E4_PASS}
    command: [ "redis-server", "--requirepass", "${DB_REDIS_AUTH_E7E4_PASS}", "--appendonly", "yes" ]
    networks:
      - portabase
      - default


volumes:
  db-valkey-auth-ca0c-data:
  db-redis-auth-e7e4-data:


networks:
  portabase:
    name: portabase_network
    external: true