name: ${PROJECT_NAME}
services:
  app:
    container_name: ${PROJECT_NAME}-app
    restart: always
    image: portabase/agent:latest
    volumes:
      - ./databases.json:/config/config.json
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      TZ: "Europe/Paris"
      EDGE_KEY: "${EDGE_KEY}"
      LOG: info
    networks:
      - portabase


  db-firebird-6f29:
    image: firebirdsql/firebird
    restart: unless-stopped
    networks:
      - portabase
    ports:
      - "${DB_FIREBIRD_6F29_PORT}:3050"
    volumes:
      - db-firebird-6f29-data:/var/lib/firebird/data
    environment:
      - FIREBIRD_DATABASE=${DB_FIREBIRD_6F29_DB}
      - FIREBIRD_USER=${DB_FIREBIRD_6F29_USER}
      - FIREBIRD_PASSWORD=${DB_FIREBIRD_6F29_PASS}
      - FIREBIRD_ROOT_PASSWORD=${DB_FIREBIRD_6F29_ROOT_PASS}
      - FIREBIRD_DATABASE_DEFAULT_CHARSET=UTF8
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 3050"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  db-firebird-6f29-data:


networks:
  portabase:
    name: portabase_network
    external: true