services:
  app:
    restart: unless-stopped
    image: portabase/agent:latest
    volumes:
      - ./databases.json:/config/config.json
    environment:
      TZ: "${TZ}"
      EDGE_KEY: "${EDGE_KEY}"
      LOG_LEVEL: "${LOG_LEVEL}"
      POLLING: "${POLLING}"
      DATA_PATH: "${DATA_PATH}"
    networks:
      - portabase

{{EXTRA_SERVICES}}

{{EXTRA_VOLUMES}}

networks:
  portabase:
    name: portabase_network
    external: true
