name: Publish release

on:
  workflow_call:
    inputs:
      prerelease:
        required: true
        type: boolean

permissions: {}

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Download binaries
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: portabase_*
          path: dist
          merge-multiple: true

      - name: Generate checksums
        working-directory: dist
        run: sha256sum * > checksums.txt

      - name: Build changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@cb021f9b36a51a7c6f18e4679b6fa2cb77a1260c # v6.3.0
        with:
          mode: COMMIT
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}",
              "categories": [
                { "title": "## Feature", "labels": ["feat", "feature"] },
                { "title": "## Fix", "labels": ["fix", "bug"] },
                { "title": "## Other", "labels": [] }
              ],
              "label_extractor": [
                {
                  "pattern": "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                  "on_property": "title",
                  "target": "$1"
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          files: dist/*
          generate_release_notes: false
          body: ${{ steps.changelog.outputs.changelog }}
          prerelease: ${{ inputs.prerelease }}
          make_latest: ${{ !inputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
